AZURE_SQL_CONN_STR = "Driver={ODBC Driver 18 for SQL Server};Server=tcp:traffics-server.database.windows.net,1433;Initial Catalog=TrafficDB;Uid=sqladmin;Pwd=admin123#;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

ALERT_EMAIL_FROM = "ki30411202500816@depi.eui.edu.eg"
ALERT_EMAIL_TO = "ae30603138801056@depi.eui.edu.eg"
ALERT_EMAIL_PASSWORD = "password123456###"
